shop/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using shop.BLL.BusinessModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace shop.Web.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart _cart;
        public CartSummaryViewComponent(Cart cart)
        {
            _cart = cart;
        }
        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

shop/Controllers/AdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using AutoMapper;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using shop.DAL.Models;
using shop.BLL.Interfaces.Services;
using shop.Web.Resources;

namespace shop.Web.Controllers
{
    public class AdminController : Controller
    {
        private IProductService _productService;
        private ICategoryService _categoryService;
        private IColorService _colorService;
        private IMapper _mapper;
        public AdminController(IProductService productService, ICategoryService categoryService, IColorService colorService, IMapper mapper)
        {
            _productService = productService;
            _categoryService = categoryService;
            _colorService = colorService;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var products = await _productService.GetProducts();
            var productResource = _mapper.Map<IEnumerable<Product>, IEnumerable<ProductResources>>(products);
            return View(productResource);
        }
        public async Task<ViewResult> Edit(int ProductId)
        {
            var categories = _categoryService.GetCategories();
            ViewBag.Categories = new SelectList(categories, "Id", "Name", categories.FirstOrDefault());
            var colors = _colorService.GetColors();
            ViewBag.Colors = new SelectList(colors, "Id", "Name", colors.FirstOrDefault());
            return View(await _productService.GetProduct(ProductId));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int ProductId, EditProductResource receivedProduct)
        {
            var updatedProduct = await _productService.GetProduct(ProductId);
            if (updatedProduct == null)
            {
                TempData["message"] = "Selected product was not found";
                return RedirectToAction("Index");
            }
            var product = _mapper.Map<EditProductResource, Product>(receivedProduct);
            if (await _productService.EditProduct(updatedProduct, product))
            {
                TempData["message"] = "Selected product was edited";
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Product product)
        {
            if (await _productService.DeleteProduct(product))
            {
                TempData["message"] = "Selected product was deleted";
            }
            return RedirectToAction("Index");
        }
    }
}

shop/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using shop.BLL.BusinessModel;
using shop.DAL;
using shop.DAL.Interfaces;
using shop.DAL.Models;
using shop.BLL.Interfaces.Services;

namespace shop.Web.Controllers
{
    public class OrderController : Controller
    {
        private Cart _cart;
        private IOrderService _orderService;
        public OrderController(Cart cart, IOrderService orderService)
        {
            _cart = cart;
            _orderService = orderService;
        }
        public IActionResult List() => View( _orderService.GetOrderByShipped(false));
        [HttpPost]
        public async Task<IActionResult> MarkShipped(int OrderId)
        {
            Order order = await _orderService.GetOrderToShipped(OrderId);
            if(order != null)
            {
                order.Shipped = true;
                await _orderService.SaveOrder(order);
            }
            return RedirectToAction(nameof(List));
        }
        public IActionResult Checkout()
        {
            return View(new Order());
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            if (!_cart.Lines.Any())
            {
                ModelState.AddModelError("", "Your cart is empty");
            }
            if (ModelState.IsValid)
            {
                order.Lines = _cart.Lines.ToArray();
                await _orderService.SaveOrder(order);
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(order);
            }
        }
        public ViewResult Completed()
        {
            _cart.Clear();
            return View();
        }
    }
}

shop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using shop.DAL;
using shop.DAL.Interfaces;
using shop.Web.ViewModel;

namespace shop.Web.Controllers
{
    public class ProductController : Controller
    {
        private IUnitOfWork _unitOfWork;
        public int PageSize = 6;
        public ProductController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index(string category, int page = 1)
        {
            return View(new ProductViewModel
            {
                Products = _unitOfWork.Products.Find(p => category == null || p.Category.Name == category)
                    .OrderBy(p => p.ProductId)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? _unitOfWork.Products.Count() :
                        _unitOfWork.Products.Count(p => p.Category.Name == category)
                },
                CurrentCategory = category
            }); 
        }
        public async Task<IActionResult> Details(string returnUrl, int productId, string name)
        {
            return View(new DetailsViewModel
            {
                AvailableColor = await _unitOfWork.Products.GetColor(name),
                Product = await _unitOfWork.Products.GetProduct(productId),
                ReturnUrl = returnUrl
            });
        }
    }
}

shop/Views/Shared/ProductSummary.cshtml
@model Product
	<div class="mdl-cell mdl-cell--middle">
		<div class="mdl-card--border mdl-shadow--6dp">
			<figure class="mdl-card__media mdl-color--grey-200">
				<img class="img-fluid" src="~/images/image0.png" />
			</figure>
			<div class="text-fluid">
				<div class="mdl-card__title">
					<h1 class="mdl-card__title-text">@Model.Name</h1>
				</div>
				<div class="mdl-card__supporting-text">
					<p>Цена: @Model.Price.ToString("c")</p>
				</div>
			</div>
			<div class="mdl-card__actions mdl-card--border">
				<form id=@Model.ProductId asp-action=AddToCart asp-controller=Cart method=post>
					<input type=hidden asp-for=ProductId />
					<input type=hidden name=returnUrl value=@ViewContext.HttpContext.Request.PathAndQuery() />
					<button type=submit class="mdl-button mdl-js-button mdl-js-ripple-effect">
						Хочу!
					</button>
				</form>
				<form id=@Model.ProductId asp-action=Details method=get>
					<input type=hidden asp-for=ProductId />
					<input type=hidden asp-for=Name />
					<input type=hidden name=returnUrl value=@ViewContext.HttpContext.Request.PathAndQuery() />
					<button type="submit" class="mdl-button mdl-js-button mdl-js-ripple-effect">
						Подробнее
					</button>
				</form>
			</div>
		</div>
	</div>

shop/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no" />
	<title>@ViewBag.Title</title>
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/lib/MDL/material.min.css" />
	<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,500,400italic,700,700italic' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="mdl-base">
	<div class="mdl-layout mdl-js-layout mdl-color--grey-200">
		<header class="mdl-layout__header mdl-layout__header--waterfall-hide-top mdl-color--grey-700">
			<div class="mdl-layout__header-row">
				<span class="mdl-layout-title">Admin panel</span>
				<div class="mdl-layout-spacer"></div>
				<nav class="mdl-navigation">
					<a class="mdl-navigation__link" asp-area="" asp-controller="Admin" asp-action="Index">Main</a>
					<a class="mdl-navigation__link" asp-area="" asp-controller="Order" asp-action="List">Orders</a>
					<a class="mdl-navigation__link" asp-area="" asp-controller="Product" asp-action="Index"></a>
					<a class="mdl-navigation__link" asp-area="" asp-controller="Home" asp-action="Index">Back to Shop</a>
				</nav>
			</div>
		</header>
		<div class="mdl-layout__drawer">
			<span class="mdl-layout-title">Admin panel</span>
			<nav class="mdl-navigation">
				<a class="mdl-navigation__link" asp-area="" asp-controller="Admin" asp-action="Index">Main</a>
				<a class="mdl-navigation__link" asp-area="" asp-controller="Order" asp-action="List">Orders</a>
				<a class="mdl-navigation__link" asp-area="" asp-controller="Product" asp-action="Index"></a>
				<a class="mdl-navigation__link" asp-area="" asp-controller="Home" asp-action="Index">Back to Shop</a>
			</nav>
		</div>
		<main class="mdl-layout__content">
			@if (TempData["message"] != null)
			{
				<div class="d-flex justify-content-center mdl-card--expand">
					<div class="mdl-card__title">
						<div class="mdl-card__title-text  mdl-color-text--light-green-700">@TempData["message"]</div>
					</div>
				</div>
			}
			<div class="d-flex justify-content-center mdl-grid mdl-color--grey-200">
				@RenderBody()
			</div>
		</main>
		<footer class="d-flex justify-content-center footer mdl-mini-footer mdl-color--grey-700 mdl-cell--hide-phone mdl-cell--hide-tablet">
			<ul class="mdl-mini-footer--link-list">
				<li>
					<a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
				</li>
				<li>
					<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
				</li>
				<li>Using MDL - 2020</li>
			</ul>
		</footer>
	</div>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/MDL/material.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>

shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no" />
    <title>@ViewData["Title"] - Monolith</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/MDL/material.min.css" />
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,500,400italic,700,700italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="mdl-base">
    <div class="mdl-layout mdl-js-layout mdl-color--grey-200">
        <header class="mdl-layout__header mdl-layout__header--waterfall-hide-top mdl-color--grey-700">
            <div class="mdl-layout__header-row">
                <span class="mdl-layout-title">Monolith</span>
                <div class="mdl-layout-spacer"></div>
                <nav class="mdl-navigation">
                    <div>
                        @await Component.InvokeAsync("CartSummary")
                    </div>
                    <a class="mdl-navigation__link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="mdl-navigation__link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    <a class="mdl-navigation__link" asp-area="" asp-controller="Product" asp-action="Index">All clothes</a>
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">Monolith</span>
            <nav class="mdl-navigation">
                <a class="mdl-navigation__link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <a class="mdl-navigation__link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                <a class="mdl-navigation__link" asp-action="Index" asp-controller="Product" asp-route-category="">All clothes</a>
            </nav>
        </div>
        <main class="mdl-layout__content">
            <div class="d-flex justify-content-center mdl-grid mdl-color--grey-200">
                    @RenderBody()
            </div>
        </main>
            <footer class="d-flex justify-content-center footer mdl-mini-footer mdl-color--grey-700 mdl-cell--hide-phone mdl-cell--hide-tablet">
				<ul class="mdl-mini-footer--link-list">
					<li>
						<a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
					</li>
					<li>
						<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
					</li>
					<li>Using MDL - 2020</li>
				</ul>
            </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/MDL/material.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>