shop/Components/NavigationМenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using shop.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace shop.Web.Components
{
    public class NavigationМenuViewComponent : ViewComponent
    {
        private IUnitOfWork _unitOfWork;
        public NavigationМenuViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(_unitOfWork.Categories.GetAllAsync());
        }
    }
}

shop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using shop.DAL;
using shop.DAL.Interfaces;
using shop.Web.ViewModel;

namespace shop.Web.Controllers
{
    public class ProductController : Controller
    {
        private IUnitOfWork _unitOfWork;
        public int PageSize = 6;
        public ProductController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index(string category, int page = 1)
        {
            return View(new ProductViewModel
            {
                Products = _unitOfWork.Products.Find(p => category == null || p.Category.Name == category)
                    .OrderBy(p => p.ProductId)
                    .Skip((page - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ? _unitOfWork.Products.Count() :
                        _unitOfWork.Products.Count(p => p.Category.Name == category)
                },
                CurrentCategory = category
            }); 
        }
        public async Task<IActionResult> Details(string returnUrl, int productId, string name)
        {
            return View(new DetailsViewModel
            {
                AvailableColor = await _unitOfWork.Products.GetColor(name),
                Product = await _unitOfWork.Products.GetProduct(productId),
                ReturnUrl = returnUrl
            });
        }
    }
}

shop/Views/Product/Details.cshtml
@model DetailsViewModel

	<div class="d-flex justify-content-center mdl-grid">

		<div class="mdl-cell mdl-cell--2-col mdl-card mdl-card--border
				mdl-shadow--6dp mdl-color--grey-100">
			<div class="mdl-grid">
				<ul class="mdl-list">
					<li class="mdl-list__item">
						<span class="mdl-list__item-primary-content">
							Доступные цвета:
						</span>
					</li>
					@foreach (var item in Model.AvailableColor)
					{
						<li class="mdl-list__item">
							<span class="mdl-list__item-primary-content">
								@item
							</span>
						</li>
					}
				</ul>
			</div>
		</div>
		<div class="mdl-cell mdl-cell--4-col mdl-card mdl-card--border
				mdl-shadow--6dp mdl-color--grey-100">
			<div class="mdl-grid">
				<img class="image-fluid" src="~/images/image0.png" />
			</div>
		</div>
		<div class="mdl-cell mdl-cell--3-col
             mdl-card mdl-card--border
             mdl-shadow--6dp mdl-color--grey-100">
			<ul class="mdl-list">
				<li class="mdl-list__item"><h4>Описание: @Model.Product.Notes</h4></li>
				<li class="mdl-list__item"><h5>Цена: @Model.Product.Price.ToString("c");</h5></li>
			</ul>
		</div>
		<div class="mdl-cell text-center">
			<a class="action-text mdl-button mdl-color-text--grey-700 mdl-js-button mdl-js-ripple-effect"
			   href="@Model.ReturnUrl">
				Back to List
			</a>
		</div>
	</div>

shop/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Products";
}
@model ProductViewModel
    <div class="mdl-cell--3-col mdl-grid mdl-cell--hide-phone mdl-cell--hide-tablet">
        @await Component.InvokeAsync("NavigationМenu")
    </div>
    <div class="mdl-cell--8-col mdl-grid">
        @foreach (var p in Model.Products)
        {
            @Html.Partial("ProductSummary", p);
        }
        <nav class="page d-flex justify-content-center mdl-cell--12-col">
            <div page-model="@Model.PagingInfo" page-action="Index"
                 page-classes-enabled="true"
                 page-class="mdl-button"
                 page-class-normal="mdl-color-text--grey mdl-button--colored"
                 page-url-category=@Model.CurrentCategory
                 page-class-selected="mdl-js-button mdl-js-ripple-effect">
            </div>
        </nav>
    </div>